apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: ucan-crossplane-provider
spec:
  deploymentTemplate:
    spec:
      replicas: 1
      selector: {}
      template:
        metadata:
          annotations:
            prometheus.io/path: /metrics
            prometheus.io/port: "8080"
            prometheus.io/scrape: "true"
        spec:
          serviceAccountName: provider-ucan-crossplane
          nodeSelector:
            osgalaxy.io/region: uc
          containers:
            - args:
                - --enable-management-policies
                - --debug
              name: package-runtime